#!/bin/bash
while getopts "d:s:" opt; do
    case $opt in
        d)
            # option -d is available
            export MODE=2
            export SOURCE=$OPTARG
            ;;
        s)
            # option -s is available
            export MODE=3
            export SOURCE=$OPTARG
            ;;
        \?)
            # Invalid option
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done

if [ $OPTIND -eq 1 ]; then
    # no options were specified
    export SOURCE=$1
    export DESTINATION=$2
    export MODE=1
fi

# exit if -d option passed and extra argument was provided
if [ $MODE == 2 ] && ! [ -z "$3" ]; then
    exit 1
fi

if [ -p /dev/stdin ]; then
    # piped value is available
    InputObject=$(cat /dev/stdin)
    echo "$InputObject" | python cctr.py -

else
    # accept user input until EOF
    while read line || [[ -n "$line" ]]; do
        echo "$line" | python cctr.py -
    done
fi
